shopping_list/urls.py
from django.urls import path
from . import views

app_name = 'shopping_list'
urlpatterns = [
    # ex: /
    path('', views.home, name='home'),
    # ex: /create_list
    path('create_list/', views.create_list, name='create_list'),
    # path('creating_list/', views.creating_list, name='creating_list'),
    # ex: /5
    path('list_details/<int:list_id>/', views.list_details, name='list_details'),

    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_user, name="register"),

    path('add_friend/', views.add_friend, name="add_friend"),
    path('add_friend/<int:request_id>/', views.add_friend, name="add_friend"),
    path('add_friend/<str:friend_name>/', views.add_friend, name="add_friend")
]

shopping_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('shopping_list.urls'))
]

shopping_list/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Item(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(blank=True, default=0)
    checked_off = models.BooleanField(default=False)

    class Meta:
        ordering = ['checked_off', 'name']

    def __str__(self):
        return self.name


class List(models.Model):
    user = models.ForeignKey(User, related_name="shoppinglist",
                             on_delete=models.SET_NULL,
                             null=True, blank=True)
    name = models.CharField(max_length=200)
    items = models.ManyToManyField(Item)
    created_on = models.DateTimeField('created on', auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    budget = models.IntegerField(default=0)
    shared_with = models.ManyToManyField(User, blank=True, related_name="sharedfriends")

    def was_created_recently(self):
        return self.created_on >= timezone.now()

    class Meta:
        ordering = ['-updated_on']

    def __str__(self):
        return self.name

    def share_list(self, account):
        """
        Add a friend to share list with
        """
        if account not in self.shared_with.all():
            self.shared_with.add(account)


class Friends(models.Model):
    # Cascade delete => if a user is deleted, their corresponding friend list will be deleted
    # This is one-one because, there only 1 friend list per 1 user
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    # A list of users; you can think of it as a list of primary keys to the account of who the user is friends with
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    # blank= True, because it is possible that they have no friends

    def __str__(self):
        return self.user.username

    def add_friend(self, account):
        """
        Add a new friend
        """
        # check if they're already in friends, and if not, add them
        if account not in self.friends.all():
            self.friends.add(account)

    def remove_friend(self, account):
        """
        Remove a friend
        """
        if account in self.friends.all():
            self.friends.remove(account)

    def unfriend(self, removee):
        """
        Initiate the action of unfriending someone
        """
        # person executing the friendship termination
        remover_friends_list = self

        # Remove friend from remover friend list
        remover_friends_list.remove_friend(removee)

        # Remove friend from removee friend list
        friends_list = Friends.objects.get(user=removee)
        friends_list.remove_friend(self.user)

    def is_mutual_friend(self, friend):
        """
        Is this a mutual friend?
        """
        return True if friend in self.friends.all() else False


class FriendRequest(models.Model):
    """
    A friend request consists of two parts:
        1. A SENDER who initiates the friend request
        2. A RECEIVER whom receives the friend request
    """
    # 1 user can send out any number of friend requests
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username

    def accept(self):
        """
        Accept a friend request
        Update both SENDER and RECEIVER friend lists
        """
        receiver_friend_list, created = Friends.objects.get_or_create(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list, created = Friends.objects.get_or_create(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.is_active = False
                self.save()

    def decline(self):
        """
        Decline a friend request
        It is "declined by setting the 'is_active' field to false
        """
        self.is_active = False
        self.save()

    def cancel(self):
        """
        Cancel a friend request
        The request is canceled by setting the 'is_active' field to False
        This is only different with respect to "declining" through the notification that is generated
        """
        self.is_active = False

shopping_list/forms.py
# from django import forms
from django.forms import ModelForm
from shopping_list.models import List
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateListForm(ModelForm):
    class Meta:
        model = List
        fields = ['name', 'budget']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    # overide the init function
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        # make the UserCreationForm username field have this form-control class, so it can be styled
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter username...'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter password...'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Confirm password...'})

shopping_list/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .context_processors import user_lists, incoming_friend_requests, \
    outgoing_friend_requests, current_friends, shared_lists
from .models import List, Item, Friends, FriendRequest
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def login_user(request):
    page = 'login'
    context = {'page': page}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
    return render(request, 'shopping_list/login_register.html', context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')


def register_user(request):
    page = 'register'
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            user = authenticate(request, username=user.username, password=request.POST['password1'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
    context = {'form': form, 'page': page}
    return render(request, 'shopping_list/login_register.html', context)


def index(request):
    return render(request, 'shopping_list/index.html', {})


def home(request):
    context = user_lists(request) | incoming_friend_requests(request) \
              | outgoing_friend_requests(request) | current_friends(request) | shared_lists(request)
    return render(request, 'shopping_list/home.html', context)


@login_required(login_url='/login/')
def add_friend(request, request_id=None, friend_name=None):
    user = request.user
    if request.method == 'POST':
        if request.POST.get("add_friend"):
            friend_name = request.POST.get("friend_name")
            try:
                receiver_id = User.objects.get(username=friend_name)
            except ObjectDoesNotExist:
                return HttpResponseRedirect('/')
            try:
                FriendRequest.objects.get(receiver=user, sender=receiver_id, is_active=True)
            except ObjectDoesNotExist:
                new_friend_request, created = FriendRequest.objects.get_or_create(sender=user, receiver=receiver_id)
                if not created:
                    FriendRequest.objects.filter(sender=user, receiver=receiver_id).update(is_active=True)
                else:
                    new_friend_request.save()
        elif request_id:
            current_request = FriendRequest.objects.get(id=request_id)
            if request.POST.get("accept_request"):
                current_request.accept()
            elif request.POST.get("decline_request"):
                current_request.decline()
            elif request.POST.get("cancel_request"):
                current_request.decline()
        elif friend_name:
            remover = Friends.objects.get(user=request.user)
            removee = User.objects.get(username=friend_name)
            remover.unfriend(removee)
        if request.POST.get("detail"):
            current_list_id = int(request.POST.get("detail"))
            return HttpResponseRedirect('/list_details/%i' % current_list_id)
        else:
            return HttpResponseRedirect('/')
    return render(request, 'shopping_list/home.html', {})


@login_required(login_url='/login/')
def create_list(request):
    user = request.user
    if request.method == 'POST':
        if request.POST.get("create_list"):
            list_name = request.POST.get("list_name")
            list_budget = request.POST.get("budget")
            new_list, created = List.objects.get_or_create(user=user, name=list_name, budget=list_budget)
            new_list.save()
            print(request.user)
            return HttpResponseRedirect('/list_details/%i' % new_list.id)
    context = incoming_friend_requests(request) | outgoing_friend_requests(request) \
              | current_friends(request) | shared_lists(request)
    return render(request, 'shopping_list/create_list.html', context)


@login_required(login_url='/login/')
def list_details(request, list_id):
    current_list = get_object_or_404(List, id=list_id)
    if request.method == 'POST':
        if current_list in request.user.shoppinglist.all() or current_list in request.user.sharedfriends.all():
            if request.POST.get("add_item"):
                item_name = request.POST.get("item_name")
                item_price = request.POST.get("item_price")
                item = Item(name=item_name, price=item_price)
                item.save()
                current_list.items.add(item)
                print(request.user)
                return HttpResponseRedirect('/list_details/%i' % list_id)
            if request.POST.get("remove_item"):
                item_id_list = request.POST.getlist("item")
                for item_id in item_id_list:
                    current_item = get_object_or_404(Item, pk=item_id)
                    current_list.items.remove(current_item)
                return HttpResponseRedirect('/list_details/%i' % list_id)
            if request.POST.get("remove_list"):
                current_list.delete()
                return HttpResponseRedirect('/')
            if request.POST.get("edit_list"):
                if request.POST.get("new_list_name"):
                    new_list_name = request.POST.get("new_list_name")
                    current_list.name = new_list_name
                if request.POST.get("new_list_budget"):
                    new_list_budget = request.POST.get("new_list_budget")
                    current_list.budget = new_list_budget
                current_list.save()
                return HttpResponseRedirect('/list_details/%i' % list_id)
            if request.POST.get("edit_item"):
                item_id = request.POST.get("edit_item")
                if request.POST.get("new_item_name"):
                    new_item_name = request.POST.get("new_item_name")
                    current_list.items.filter(pk=item_id).update(name=new_item_name)
                if request.POST.get("new_item_price"):
                    new_item_price = request.POST.get("new_item_price")
                    current_list.items.filter(pk=item_id).update(price=new_item_price)
                current_list.save()
                return HttpResponseRedirect('/list_details/%i' % list_id)
            if request.POST.get("share_list"):
                friend_name = request.POST.get("share_list")
                friend_obj = User.objects.get(username=friend_name)
                current_list.share_list(friend_obj)
                return HttpResponseRedirect('/list_details/%i' % list_id)
        else:
            return HttpResponse("YOU DON'T HAVE PERMISSION TO EDIT THIS LIST!")
    elif current_list in request.user.shoppinglist.all() or current_list in request.user.sharedfriends.all():
        unauthorized_friends = User.objects.filter(friends__user=request.user).exclude(sharedfriends__user__is_active=True)
        authorized_friends = User.objects.filter(sharedfriends__user__username=current_list.user)
        context = {'current_list': current_list} | user_lists(request) | incoming_friend_requests(request) \
                  | outgoing_friend_requests(request) | current_friends(request) | shared_lists(request)\
                  | {'unauthorized_friends': unauthorized_friends} | {'authorized_friends': authorized_friends}\
                  | {'page': 'detail'}
        return render(request, 'shopping_list/detail.html', context)
    else:
        return HttpResponse("YOU DON'T HAVE ACCESS TO THIS PAGE!")

shopping_list/templates/shopping_list/create_list.html
{%  extends "shopping_list/index.html" %}
{%  load static %}

{% block title %}Create List{% endblock %}

{% block content %}
    <form class="pt-5 form-group row" method="POST" action="#">
        {% csrf_token %}
        <div class="mb-3 col-4">
            <label for="list_name" class="form-label">List Name</label>
            <input id="list_name" type="text" name="list_name" class="form-control" aria-describedby="list-name">
        </div>
        <div class="mb-3 col-4">
            <label for="budget" class="form-label">Budget</label>
            <input id="budget" type="number" name="budget" class="form-control">
        </div>
        <div class="row-cols-3 align-item-center">
            <button type="submit" name="create_list" value="create_list" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock %}

shopping_list/templates/shopping_list/detail.html
{%  extends "shopping_list/index.html" %}

{%  load static %}

{% block title %}{{ current_list.name }} List Details{% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}

        <!-- Add Item to List -->
        <form action="#" method="post" class="form-group form-inline">
            {% csrf_token %}
            <div class="row w-50 mx-auto mb-6 pb-6">
                <div class="mt-3 col">
                    <label for="item_name" class="sr-only">Name</label>
                    <input type="text" class="form-control" id="item_name" name="item_name" placeholder="Item Name">
                </div>
                <div class="mt-3 col">
                    <label for="item_price" class="sr-only">Price</label>
                    <input type="text" class="form-control" id="item_price" name="item_price" placeholder="Price">
                </div>
                <div class="mt-3 col">
                    <button type="submit" name="add_item" value="add_item" class="btn btn-primary mb-2">Add to List</button>
                </div>
            </div>
        </form>

        <form action="#" method="post" class="form-group form-inline">
            {% csrf_token %}
            <fieldset class="field_set form-group p-3 row">
                <legend class="col-auto">
                    <h1>{{ current_list.name }} (${{ current_list.budget }} budget)</h1>
                </legend>

                <!-- Edit List Trigger Modal -->
                <button type="button" name="edit_list" value="edit_list" class="col-auto btn btn-danger" data-bs-toggle="modal" data-bs-target="#editList">
                    Edit List
                </button>
                <!-- Edit List Modal -->
                <div class="modal fade" id="editList" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="editListLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editListLabel">Enter new list name and budget for {{ current_list.name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="mb-3 input-group">
                                <label for="new_list_name" class="col-form-label">New List Name:</label>
                                <input type="text" class="form-control" name="new_list_name" id="new_list_name">
                            </div>
                            <div class="mb-3 input-group">
                                <label for="new_list_budget" class="col-form-label">New List Budget:</label>
                                <textarea class="form-control" name="new_list_budget" id="new_list_budget"></textarea>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" name="edit_list" value="edit_list" class="btn btn-success btn-outline-dark">Submit</button>
                                <button type="button" class="btn btn-danger btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Share List Trigger Modal -->
                <button type="button" name="share_list" value="share_list" class="col-auto btn btn-danger" data-bs-toggle="modal" data-bs-target="#shareList">
                    Share with Friend
                </button>
                <!-- Share List Modal -->
                <div class="modal fade" id="shareList" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="shareListLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            {% if unauthorized_friends %}
                                {% for friend in unauthorized_friends %}
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="shareListLabel">Choose a friend to share this list with: </h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="mb-3 input-group">
                                        <input type="checkbox" name="friend" id="friend{{ forloop.counter }}" value="{{ friend.id }}">
                                        <label for="friend{{ forloop.counter }}">{{ friend }}</label>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="submit" name="share_list" value="{{ friend }}" class="btn btn-success btn-outline-dark">Submit</button>
                                        <button type="button" class="btn btn-danger btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class="modal-header">
                                    <h5 class="modal-title" id="shareListLabel">You have no (more) friends to share this list with.</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <!-- List of Items -->
                <div class="row position-relative justify-content-start">
                    <div class="col">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                        {% for item in current_list.items.all %}
                            <input type="checkbox" name="item" id="item{{ forloop.counter }}" value="{{ item.id }}">
                            <label for="item{{ forloop.counter }}">{{ item.name }} (price: ${{ item.price }})</label>
                            <!-- Edit Item Trigger Modal -->
                            <button type="button" name="edit_item" value="{{ item.id }}" class="col-auto btn btn-danger" data-bs-toggle="modal" data-bs-target="#editItem">
                                Edit Item
                            </button><br>
                            <!-- Edit Item Modal -->
                            <div class="modal fade" id="editItem" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="editItemLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="editItemLabel">Enter new item name and cost for {{ item.name }}</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="mb-3 input-group">
                                            <label for="new_item_name" class="col-form-label">Edited Item Name:</label>
                                            <input type="text" class="form-control" name="new_item_name" id="new_item_name">
                                        </div>
                                        <div class="mb-3 input-group">
                                            <label for="new_item_price" class="col-form-label">New Item Price:</label>
                                            <textarea class="form-control" name="new_item_price" id="new_item_price"></textarea>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" name="edit_item" value="{{ item.id }}" class="btn btn-success btn-outline-dark">Submit</button>
                                            <button type="button" class="btn btn-danger btn-outline-dark" data-bs-dismiss="modal">No</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="">
                        <button type="submit" name="remove_item" value="remove_item" class="btn btn-danger btn-outline-primary mb-2">Remove Item</button>
                    </div>
                </div>
            </fieldset>

            <!-- Deletion Button Trigger Modal -->
            <button type="button" name="remove_list" value="remove_list" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeletion">
                !!!DELETE LIST!!!
            </button>
            <!-- Deletion Modal -->
            <div class="modal fade" id="confirmDeletion" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="confirmDeletionLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmDeletionLabel">Warning! {{ current_list.name }} will be deleted FOREVER!</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this shopping list?
                        </div>
                        <div class="modal-footer">
                            <button type="submit" name="remove_list" value="remove_list" class="btn btn-success btn-outline-dark">Yes</button>
                            <button type="button" class="btn btn-danger btn-outline-dark" data-bs-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Owner and Authorized List Users -->
            <div class="container">
                <div class="row justify-content-around">
                    <div class="col-4">
                        List Owner: {{ current_list.user }}
                    </div>
                    <div class="col-4">
                        Users Authorized: {% for friend in authorized_friends %}{{ friend }}{% endfor %}
                    </div>
                </div>
            </div>
        </form>
    {% else %}
        <p>Login <a href={% url 'shopping_list:login' %}>Here</a></p>
    {% endif %}
{% endblock %}

shopping_list/templates/shopping_list/home.html
{%  extends "shopping_list/index.html" %}
{%  load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="row">
        <div id="create-list" class="col align-self-center">
            <i class="fa fa-briefcase"></i>
            <p>What are you waiting for? Let's get this shopping list organized!</p>
            <form class="row form-inline" action="create_list/" method="post">
                {% csrf_token %}
{#                    TODO: make logic so if you type an already existing list name, it prompts whether you want to create a new list or edit that list#}
                <div class="col-auto">
                    <button class="btn btn-primary" type="submit" id="create-button-home">Create List</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

shopping_list/templates/shopping_list/login_register.html
{%  extends "shopping_list/index.html" %}
{%  load static %}

{% block title %}Login{% endblock %}

{% block content %}
    {% if page == 'login' %}
    <div class="container">
        <div class="login-wrapper">
            <form class="login-form" method="POST" action="#">
{#            <form class="login-form pt-5 form-group row" method="POST" action="#">#}
                {% csrf_token %}
                <h1>Login</h1>
                <h4>Login to view your saved lists and share with others!</h4>
                <div class="mb-3 col-4">
                    <label for="inputUsername" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" id="inputUsername" aria-describedby="emailHelp">
                </div>
                <div class="mb-3 col-4">
                    <label for="inputPassword" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="inputPassword">
                </div>
                <button type="submit" name="submit_login" value="submit_login" class="btn btn-primary">Submit</button>
                <p>Don't have an account? <a href={% url 'shopping_list:register' %}>Register Now</a></p>
            </form>
        </div>
    </div>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            <h1>Register</h1>
            {{ form }}
            <button type="submit" name="submit_login" value="submit_login" class="btn btn-primary">Submit</button>
            <p>Already have an account? <a href={% url 'shopping_list:login' %}>Login Now</a></p>
        </form>
    {% endif %}
{% endblock %}